name: AndiamoM2
favicon: null
layout_spectrum: 0.2631
typography_spectrum: 0.00105
title: 'Welcome to the most authentic Italian food in Abu Dhabi!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.8020638360176235
  lightness: 0.3323075398802757
  saturation: 0.6961862086318433
  rhythmicContrast: 0.2574107216205448
purpose: []
